### ISSUE TITLE
broken bulk_elem ids array in boundary mesh

### ISSUE THREAD

**Issue by joergbuchwald** [dominik-kern/msh2vtu#2]
Creating a vtu mesh using the command `python3 msh2vtu.py --ogs --rdcd mesh_test.msh` from the following mesh file
[mesh_test.msh](https://github.com/joergbuchwald/mini-projects/blob/master/temp/mesh_test.msh) 
creates a mesh with an associated boundary mesh (`mesh_test_physical_group_heaterb.vtu`) containing a broken `bulk_elem_ids` array. This broken array causes a crash in paraview as well a OGS.
Deleting the entire array manually fixes the problem.

**Comment by dominik-kern** [comment]
Thank you for the reported bug. I can reproduce it and will try to fix it.

**Comment by dominik-kern** [comment]
The trouble is that there are line-elements left inside the domain, so these lines are part of two triangle-elements, which of them should be chosen as bulk-element?
Currently msh2vtu assumes that elements of (dimension-1) are only located at the boundaries.
What do you intend by inner elements of boundary-dimension and how do you want msh2vtu to handle this?
Right now there is a zero left, if no domain cell could be assigned uniquely, which is an invalid number.
Do you wish to chose one by random or to have the option to exclude certain physical groups from the boundary?
Or maybe it is best to exclude them from the boundary, i.e. if there are more than one domain elements connected then the element cannot be part of a boundary and will not be stored?

**Comment by dominik-kern** [comment]
![buchwald](https://user-images.githubusercontent.com/67634130/102195365-c6814100-3ebe-11eb-8fe8-7a8c4382bbc5.png)
troublemaker

**Comment by joergbuchwald** [comment]
The purpose is to use a medium interface as a boundary, where boundary really acts in both directions. This makes sense, e.g., in case for THM coupling, if one has more than one process; it can act then as a Dirichtlet boundary for the temperature, but it is just a normal media interface for p and u.
AFAIK, OGS does not use them, it only uses bulk_node_ids, so I don't really care if would just delete them.
However, I think the best idea is to create two arrays and to make one array the standard array dependent on the physical group.
It really depends on where these properties are used which goes little be beyond my knowledge, maybe it even is better to create two boundary files for each physical group. This solution would only make sense if you would have to assign each boundary condition to a cell/physical group to work. As OGS users are the major target group right now, creating just two arrays is enough, I think.

**Comment by dominik-kern** [comment]
OK, to sum up, there will be meshes
- for the complete boundary containing only real boundaries, i.e. only with one bulk_elem_id per boundary element
- for physical groups on boundaries with one bulk_elem_id per element
- for physical groups of boundary dimension inside the domain without storing a bulk_elem_id

bulk_node_ids will be stored for all of them.

I will think overnight and start implementing tomorrow after JC.

**Comment by dominik-kern** [comment]
Done. The rare case of physical groups with elements of boundary dimension at both boundary and inside domain does not store any bulk_elem_ids, but gives a warning recommending to create separate physical groups, if bulk_elem_ids at the boundary are needed.
