### ISSUE TITLE
IndexError with msh2vtu

### ISSUE THREAD

**Issue by emartincb** [dominik-kern/msh2vtu#3]
Hello all,

I was trying to convert .msh file to vtu files with msh2vtu.py but when I run it, the terminal return this error:

--> python3 msh2vtu.py mesh.msh

MeshIO 5.3.4 found, MSH2VTU was tested with MeshIO 4.4.8.
Newer version of MeshIO than supported. Backward compatibility may be missing!
MeshIO version > 5.0 brings relevant changes. MSH2VTU will catch up as PyVista does so.

Original mesh (read)
1086 points in 3 dimensions; cells: 87 line, 2017 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical', 'gmsh:geometrical']; cell_sets=['null flux boundary', 'hydraulic head', 'tailings', 'starter_dam', 'erosion', 'gmsh:bounding_entities']

Trying to save original mesh as vtu-file (possibly not all features may be saved)
Info: VTU format cannot write cell_sets. Converting them to cell_data...
Traceback (most recent call last):
File "/home/eloy/Documentos/Merriespruit_mesh/msh2vtu.py", line 210, in
meshio.write(output_basename + "_original.vtu", mesh, binary=not args.ascii)
File "/home/eloy/.local/lib/python3.10/site-packages/meshio/_helpers.py", line 188, in write
return writer(filename, mesh, **kwargs)
File "/home/eloy/.local/lib/python3.10/site-packages/meshio/vtu/_vtu.py", line 644, in write
mesh.cell_sets_to_data(key)
File "/home/eloy/.local/lib/python3.10/site-packages/meshio/_mesh.py", line 328, in cell_sets_to_data
arr[cc] = i
IndexError: index 14 is out of bounds for axis 0 with size 13

Is it a geometry issue?

Thanks a lot.

Regards,
MC

**Comment by dominik-kern** [comment]
msh2vtu relies on Gmsh and MeshIO which over the versions differ how data are structured.
Unfortunately msh2vtu is not adapting to different versions, but trying to keep up with the latest ones.
Anyway, if you attach your msh-file, I will take a look at it.

**Comment by emartincb** [comment]
Thanks you sr. Attach the msh-file:

# required libraries
import gmsh

# general options gmsh
gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
gmsh.model.add("model")

# mesh refinement variables
mr_1 = 2.5
mr_2 = 1.5
mr_3 = 1.0

# points
gmsh.model.geo.addPoint(1, 1, 0, mr_1, 1)
gmsh.model.geo.addPoint(99.8196, 1, 0, mr_3, 2)
gmsh.model.geo.addPoint(121.0, 1, 0, mr_1, 3)
gmsh.model.geo.addPoint(109.7926, 6.3224, 0, mr_3, 4)
gmsh.model.geo.addPoint(106.8353, 10.1142, 0, mr_1, 5)
gmsh.model.geo.addPoint(96.518, 10.1142, 0, mr_1, 6)
gmsh.model.geo.addPoint(95.0728, 11.1287, 0, mr_3, 7)
gmsh.model.geo.addPoint(86.2669, 17.3136, 0, mr_1, 8)
gmsh.model.geo.addPoint(82.6969, 17.3136, 0, mr_3, 9)
gmsh.model.geo.addPoint(76.304, 17.3136, 0, mr_1, 10)
gmsh.model.geo.addPoint(62.8094, 27.1548, 0, mr_1, 11)
gmsh.model.geo.addPoint(54.3483, 27.1548, 0, mr_1, 12)
gmsh.model.geo.addPoint(47.4666, 32.0079, 0, mr_1, 13)
gmsh.model.geo.addPoint(1, 32.0079, 0, mr_1, 14)
gmsh.model.geo.addPoint(107.5912, 6.3224, 0, mr_3, 15)
gmsh.model.geo.addPoint(83.4624, 15.9349, 0, mr_3, 16)
gmsh.model.geo.addPoint(85.1565, 14.3459, 0, mr_3, 17)
gmsh.model.geo.addPoint(86.5161, 13.4072, 0, mr_3, 18)
gmsh.model.geo.addPoint(88.1234, 12.4783, 0, mr_3, 19)
gmsh.model.geo.addPoint(90.4408, 11.6464, 0, mr_3, 20)
gmsh.model.geo.addPoint(92.9475, 11.1287, 0, mr_3, 21)

# lines
gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
gmsh.model.geo.addLine(4, 5, 4)
gmsh.model.geo.addLine(5, 6, 5)
gmsh.model.geo.addLine(6, 7, 6)
gmsh.model.geo.addLine(7, 8, 7)
gmsh.model.geo.addLine(8, 9, 8)
gmsh.model.geo.addLine(9, 10, 9)
gmsh.model.geo.addLine(10, 11, 10)
gmsh.model.geo.addLine(11, 12, 11)
gmsh.model.geo.addLine(12, 13, 12)
gmsh.model.geo.addLine(13, 14, 13)
gmsh.model.geo.addLine(14, 1, 14)
gmsh.model.geo.addLine(4, 15, 15)
gmsh.model.geo.addLine(15, 2, 16)
gmsh.model.geo.addLine(9, 16, 17)
gmsh.model.geo.addLine(16, 17, 18)
gmsh.model.geo.addLine(17, 18, 19)
gmsh.model.geo.addLine(18, 19, 20)
gmsh.model.geo.addLine(19, 20, 21)
gmsh.model.geo.addLine(20, 21, 22)
gmsh.model.geo.addLine(21, 7, 23)

# curve loops
gmsh.model.geo.addCurveLoop([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 1) #tailings
#gmsh.model.geo.addCurveLoop([1, 16, 15, 4, 5, 6, 23, 22, 21, 20, 19, 18, 17, 9, 10, 11, 12, 13, 14], 1) #tailings
gmsh.model.geo.addCurveLoop([2, 3, 15, 16], 2) #starter_dam
gmsh.model.geo.addCurveLoop([17, 18, 19, 20, 21, 22, 23, 7, 8], 3) #erosion

# surfaces
gmsh.model.geo.addPlaneSurface([1, 2, 3], 1) #tailings
gmsh.model.geo.addPlaneSurface([2], 2) #starter_dam
gmsh.model.geo.addPlaneSurface([3], 3) #erosion

# physical groups
gmsh.model.addPhysicalGroup(1, [1, 2], 101)
gmsh.model.setPhysicalName(1, 101, "null flux boundary")
#gmsh.model.addPhysicalGroup(1, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], 102)
#gmsh.model.setPhysicalName(1, 102, "seepage boundary")
gmsh.model.addPhysicalGroup(1, [14], 103)
gmsh.model.setPhysicalName(1, 103, "hydraulic head")
gmsh.model.addPhysicalGroup(2, [1], 201)
gmsh.model.setPhysicalName(2, 201, "tailings")
gmsh.model.addPhysicalGroup(2, [2], 202)
gmsh.model.setPhysicalName(2, 202, "starter_dam")
gmsh.model.addPhysicalGroup(2, [3], 203)
gmsh.model.setPhysicalName(2, 203, "erosion")

# generate the mesh
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)

# visualisation options
#gmsh.option.setNumber('Geometry.Lines', 1)
gmsh.option.setNumber('Geometry.CurveLabels', 1)
#gmsh.option.setNumber('Geometry.Points', 1)
gmsh.option.setNumber('Geometry.Surfaces', 1)
gmsh.option.setNumber('Geometry.SurfaceLabels', 1)
#gmsh.option.setNumber('Mesh.SurfaceFaces', 1)

# write mesh file and show mesh
gmsh.write('mesh.msh')
gmsh.fltk.run()
gmsh.finalize()

**Comment by dominik-kern** [comment]
On my computer it seems to work, please check the attached files.
I am using the current version of msh2vtu, gmsh-4.10.5 and meshio 5.3.4 [Python 3.10.6].
[mesh.zip](https://github.com/dominik-kern/msh2vtu/files/9664313/mesh.zip)
Sorry for the hard-coded version dependencies.

**Comment by emartincb** [comment]
Many thanks sr. When I update the versions, I get your files as well, but when I try to add a new physical group line, the terminal return the previous error. Attach the py file:

# required libraries
import gmsh

# general options gmsh
gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
gmsh.model.add("model")

# mesh refinement variables
mr_1 = 2.5
mr_2 = 1.5
mr_3 = 1.0

# points
gmsh.model.geo.addPoint(1, 1, 0, mr_1, 1)
gmsh.model.geo.addPoint(99.8196, 1, 0, mr_3, 2)
gmsh.model.geo.addPoint(121.0, 1, 0, mr_1, 3)
gmsh.model.geo.addPoint(109.7926, 6.3224, 0, mr_3, 4)
gmsh.model.geo.addPoint(106.8353, 10.1142, 0, mr_1, 5)
gmsh.model.geo.addPoint(96.518, 10.1142, 0, mr_1, 6)
gmsh.model.geo.addPoint(95.0728, 11.1287, 0, mr_3, 7)
gmsh.model.geo.addPoint(86.2669, 17.3136, 0, mr_1, 8)
gmsh.model.geo.addPoint(82.6969, 17.3136, 0, mr_3, 9)
gmsh.model.geo.addPoint(76.304, 17.3136, 0, mr_1, 10)
gmsh.model.geo.addPoint(62.8094, 27.1548, 0, mr_1, 11)
gmsh.model.geo.addPoint(54.3483, 27.1548, 0, mr_1, 12)
gmsh.model.geo.addPoint(47.4666, 32.0079, 0, mr_1, 13)
gmsh.model.geo.addPoint(1, 32.0079, 0, mr_1, 14)
gmsh.model.geo.addPoint(107.5912, 6.3224, 0, mr_3, 15)
gmsh.model.geo.addPoint(83.4624, 15.9349, 0, mr_3, 16)
gmsh.model.geo.addPoint(85.1565, 14.3459, 0, mr_3, 17)
gmsh.model.geo.addPoint(86.5161, 13.4072, 0, mr_3, 18)
gmsh.model.geo.addPoint(88.1234, 12.4783, 0, mr_3, 19)
gmsh.model.geo.addPoint(90.4408, 11.6464, 0, mr_3, 20)
gmsh.model.geo.addPoint(92.9475, 11.1287, 0, mr_3, 21)

# lines
gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
gmsh.model.geo.addLine(4, 5, 4)
gmsh.model.geo.addLine(5, 6, 5)
gmsh.model.geo.addLine(6, 7, 6)
gmsh.model.geo.addLine(7, 8, 7)
gmsh.model.geo.addLine(8, 9, 8)
gmsh.model.geo.addLine(9, 10, 9)
gmsh.model.geo.addLine(10, 11, 10)
gmsh.model.geo.addLine(11, 12, 11)
gmsh.model.geo.addLine(12, 13, 12)
gmsh.model.geo.addLine(13, 14, 13)
gmsh.model.geo.addLine(14, 1, 14)
gmsh.model.geo.addLine(4, 15, 15)
gmsh.model.geo.addLine(15, 2, 16)
gmsh.model.geo.addLine(9, 16, 17)
gmsh.model.geo.addLine(16, 17, 18)
gmsh.model.geo.addLine(17, 18, 19)
gmsh.model.geo.addLine(18, 19, 20)
gmsh.model.geo.addLine(19, 20, 21)
gmsh.model.geo.addLine(20, 21, 22)
gmsh.model.geo.addLine(21, 7, 23)

# curve loops
gmsh.model.geo.addCurveLoop([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 1) #tailings
#gmsh.model.geo.addCurveLoop([1, 16, 15, 4, 5, 6, 23, 22, 21, 20, 19, 18, 17, 9, 10, 11, 12, 13, 14], 1) #tailings
gmsh.model.geo.addCurveLoop([2, 3, 15, 16], 2) #starter_dam
gmsh.model.geo.addCurveLoop([17, 18, 19, 20, 21, 22, 23, 7, 8], 3) #erosion

# surfaces
gmsh.model.geo.addPlaneSurface([1, 2, 3], 1) #tailings
gmsh.model.geo.addPlaneSurface([2], 2) #starter_dam
gmsh.model.geo.addPlaneSurface([3], 3) #erosion

# physical groups
gmsh.model.addPhysicalGroup(1, [1, 2], 101)
gmsh.model.setPhysicalName(1, 101, "null flux boundary")
gmsh.model.addPhysicalGroup(1, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], 102)
gmsh.model.setPhysicalName(1, 102, "seepage boundary")
gmsh.model.addPhysicalGroup(1, [14], 103)
gmsh.model.setPhysicalName(1, 103, "hydraulic head")
gmsh.model.addPhysicalGroup(2, [1], 201)
gmsh.model.setPhysicalName(2, 201, "tailings")
gmsh.model.addPhysicalGroup(2, [2], 202)
gmsh.model.setPhysicalName(2, 202, "starter_dam")
gmsh.model.addPhysicalGroup(2, [3], 203)
gmsh.model.setPhysicalName(2, 203, "erosion")

# generate the mesh
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)

# visualisation options
#gmsh.option.setNumber('Geometry.Lines', 1)
gmsh.option.setNumber('Geometry.CurveLabels', 1)
#gmsh.option.setNumber('Geometry.Points', 1)
gmsh.option.setNumber('Geometry.Surfaces', 1)
gmsh.option.setNumber('Geometry.SurfaceLabels', 1)
#gmsh.option.setNumber('Mesh.SurfaceFaces', 1)

# write mesh file and show mesh
gmsh.write('mesh.msh')
gmsh.fltk.run()
gmsh.finalize()

**Comment by dominik-kern** [comment]
I am afraid, it still works, files attached and output at the end.
Regard, gmsh, it is not decisive, but I recommend to run ``gmsh.model.geo.synchronize()`` before (and after, repetitions do not harm) creating physical groups.
```
Original mesh (read)
1086 points in 3 dimensions; cells: 153 line, 2017 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical', 'gmsh:geometrical']; cell_sets=['null flux boundary', 'seepage boundary', 'hydraulic head', 'tailings', 'starter_dam', 'erosion', 'gmsh:bounding_entities']
##
Detected mesh dimension: 2
##
Domain mesh (written)
1086 points in 3 dimensions; cells: 2017 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Boundary mesh (written)
153 points in 3 dimensions; cells: 153 line; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh null flux boundary (written)
75 points in 3 dimensions; cells: 74 line; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh seepage boundary (written)
67 points in 3 dimensions; cells: 66 line; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh hydraulic head (written)
14 points in 3 dimensions; cells: 13 line; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh tailings (written)
1000 points in 3 dimensions; cells: 1845 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh starter_dam (written)
70 points in 3 dimensions; cells: 104 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
Submesh erosion (written)
49 points in 3 dimensions; cells: 68 triangle; point_data=['gmsh:dim_tags']; cell_data=['gmsh:physical']; cell_sets=[]
##
[mesh.zip](https://github.com/dominik-kern/msh2vtu/files/9672670/mesh.zip)

```

**Comment by emartincb** [comment]
Thanks sr. I was working with an older version of msh2vtu, probably that was the issue.
Regards!

**Comment by emartincb** [comment]
Hello sr, I was working with the vtu files on ogs.prj. First, I could obtain good results with Small Deformations type problems, but when I work with Hydro-Mechanics problems and the same vtu files, I got this:

critical: /home/emartin/ogs/sources/ogs-master/ProcessLib/BoundaryConditionAndSourceTerm/DirichletBoundaryConditionAuxiliaryFunctions.cpp:45 checkParametersOfDirichletBoundaryCondition() 
error: The required bulk node ids map does not exist in the boundary mesh 'mesh_physical_group_hydraulic_head'.
info: OGS terminated on 2022-10-22 16:50:47+0000.
error: OGS terminated with error.

It's looks like a mesh issue, but I don't think so because I was able to work correctly with the same vtu files in a Mechanics problem.

**Comment by dominik-kern** [comment]
It is a mesh issue, the boundary mesh must _know_ where its elements are located in the bulk mesh, this is this point data field (bulk node ids) for. Since it works with SD but not with HM I assume it is related with quadratic elements (Taylor-Hood elements are recommended for HM, where as linear elements are good enough for SD). And indeed there were recently some relevant changes in the ogs tools, anyway I propose as solution
```
identifySubdomains   -m DOMAIN_MESH.vtu  -f BOUNDARY_MESH.vtu
```
